import React from 'react';
import { ArrowRight, BrainCircuit, CheckCircle2, Layers, Network } from 'lucide-react';
import { DiagnosticLog, UserProfile, ViewMode } from '../types';

interface DashboardViewProps { user: UserProfile; logs: DiagnosticLog[]; onNavigate: (view: ViewMode) => void; onSelectPracticeTopic?: (topic: string) => void; }

export const DashboardView: React.FC<DashboardViewProps> = ({ user, logs, onNavigate }) => <div className="min-h-screen bg-[#f8f9ff] px-4 py-10 sm:px-6 lg:px-8"><div className="mx-auto max-w-5xl">
  <div className="rounded-3xl bg-gradient-to-br from-[#08213d] to-[#075b85] p-8 text-white sm:p-12"><p className="text-xs font-bold uppercase tracking-[0.18em] text-cyan-200">Your private workspace</p><h1 className="mt-3 text-3xl font-extrabold tracking-tight sm:text-4xl">Welcome{user.name ? `, ${user.name}` : ''}.</h1><p className="mt-4 max-w-xl text-sm leading-7 text-slate-200">There are no preloaded results here. Start a diagnostic when you are ready, and CogniFix will build your workspace from your own learning activity.</p><button onClick={() => onNavigate('practice-and-quiz')} className="mt-7 inline-flex items-center gap-2 rounded-xl bg-cyan-300 px-5 py-3 text-sm font-bold text-[#06213a]">Start your first diagnostic <ArrowRight className="h-4 w-4" /></button></div>
  <div className="mt-8 grid gap-5 md:grid-cols-3">{[{ icon: BrainCircuit, title: 'Diagnostics', text: logs.length ? `${logs.length} learning record${logs.length === 1 ? '' : 's'} available.` : 'Your diagnostic history will appear here.' }, { icon: Network, title: 'Knowledge map', text: 'Concept connections will form as you learn.' }, { icon: Layers, title: 'Review deck', text: 'Your recall prompts will be saved here.' }].map(({ icon: Icon, title, text }) => <div key={title} className="rounded-2xl border border-slate-200 bg-white p-6"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[#e5eeff] text-[#006096]"><Icon className="h-5 w-5" /></div><h2 className="mt-5 font-bold text-[#0b1c30]">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{text}</p></div>)}</div>
  <div className="mt-8 flex items-start gap-3 rounded-2xl border border-emerald-200 bg-emerald-50 p-5 text-sm text-emerald-900"><CheckCircle2 className="mt-0.5 h-5 w-5 shrink-0 text-emerald-600" /><p>This is a fresh workspace. Only work you complete will be shown as progress or results.</p></div>
</div></div>;
