import React, { useState } from 'react';
import { Menu, Sparkles, X } from 'lucide-react';
import { ViewMode, UserProfile } from '../types';

interface HeaderProps { currentView: ViewMode; onNavigate: (view: ViewMode) => void; user: UserProfile; onOpenAuth: () => void; }

export const Header: React.FC<HeaderProps> = ({ currentView, onNavigate, user, onOpenAuth }) => {
  const [menuOpen, setMenuOpen] = useState(false);
  const items: { id: ViewMode; label: string }[] = [{ id: 'dashboard', label: 'Dashboard' }, { id: 'practice-and-quiz', label: 'Practice' }, { id: 'flashcards', label: 'Flashcards' }, { id: 'mind-map', label: 'Mind map' }, { id: 'roadmap', label: 'Roadmap' }, ...(user.role === 'teacher' ? [{ id: 'teacher-portal' as ViewMode, label: 'Teacher portal' }] : [])];
  const navigate = (view: ViewMode) => { setMenuOpen(false); onNavigate(view); };
  return <header className="sticky top-0 z-40 border-b border-slate-200/80 bg-white/90 backdrop-blur-xl"><div className="mx-auto flex h-[4.5rem] max-w-7xl items-center justify-between px-5 sm:px-8 lg:px-10"><button onClick={() => navigate('landing')} className="flex items-center gap-2.5 text-left"><span className="grid h-9 w-9 place-items-center rounded-xl bg-gradient-to-br from-[#006096] to-[#00a6c7] text-white shadow-lg shadow-cyan-700/15"><Sparkles className="h-5 w-5" /></span><span><span className="block text-base font-extrabold tracking-tight text-[#0b1c30]">Cogni<span className="text-[#007abc]">Fix</span></span><span className="block text-[9px] font-bold uppercase tracking-[0.14em] text-slate-500">Learn with clarity</span></span></button>{currentView === 'landing' ? <button onClick={onOpenAuth} className="rounded-lg bg-[#006096] px-4 py-2 text-xs font-bold text-white transition hover:bg-[#007abc]">Sign in</button> : <><nav className="hidden items-center gap-1 lg:flex">{items.map(item => <button key={item.id} onClick={() => navigate(item.id)} className={`rounded-lg px-3 py-2 text-xs font-semibold transition ${currentView === item.id ? 'bg-[#e5eeff] text-[#006096]' : 'text-slate-600 hover:bg-slate-100 hover:text-slate-950'}`}>{item.label}</button>)}</nav><div className="flex items-center gap-2"><button onClick={onOpenAuth} className="hidden rounded-lg border border-slate-200 px-3 py-2 text-xs font-semibold text-slate-700 sm:block">{user.isGuest ? 'Account' : user.name}</button><button onClick={() => setMenuOpen(!menuOpen)} className="grid h-9 w-9 place-items-center rounded-lg border border-slate-200 text-slate-700 lg:hidden" aria-label="Open navigation">{menuOpen ? <X className="h-4 w-4" /> : <Menu className="h-4 w-4" />}</button></div></>}</div>{menuOpen && currentView !== 'landing' && <nav className="border-t border-slate-100 bg-white px-5 py-3 lg:hidden"><div className="mx-auto grid max-w-7xl grid-cols-2 gap-2">{items.map(item => <button key={item.id} onClick={() => navigate(item.id)} className="rounded-lg bg-slate-50 px-3 py-2.5 text-left text-xs font-semibold text-slate-700">{item.label}</button>)}</div></nav>}</header>;
};
